author: Eduard Georgiev
url: https://ergeorgiev.com/
description: Ed's projects.

permalink: /:slug

favicon: "./logo.png"

twitter:
    username: ergeorgiev
    card: summary_large_image

remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "dark"

highlighter: rouge

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-soopr-seo-tag
